services:
  app:
    build:
      context: ./app
    container_name: app
    environment:
      - APP_NAME=demo-app
      - APP_VERSION=0.1.0
      - GIT_COMMIT=local
    ports:
      - "8000:8000"
    networks: [mon]

  nginx:
    image: nginx:1.25
    container_name: nginx
    depends_on: [app]
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks: [mon]
  
  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    networks: [mon]



  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data:/prometheus
    networks: [mon]



  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    networks: [mon]


  grafana:
    image: grafana/grafana:12.4.0-20977568970-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks: [mon]
  

  loki:
    image: grafana/loki:k290-cc5b259
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/local-config.yaml"]
    networks: [mon]


  promtail:
    image: grafana/promtail:main-e0370b1
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    command: ["-config.file=/etc/promtail/config.yml"]
    depends_on: [loki]
    networks: [mon]
  

networks:
  mon:
    driver: bridge
