upstream backend {
    server app:8000;
}

server {
    listen 80;

    # сайт
    location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
    }

    # проксируем API
    location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Request-Id $request_id;
    }

    # health backend через nginx
    location /health {
        proxy_pass http://backend/health;
    }

    # метрики backend (можно закрыть позже allow/deny)
    location /app-metrics {
        proxy_pass http://backend/metrics;
    }

    # stub_status для nginx-exporter
    location /stub_status {
        stub_status;
        allow all; # для начала. Потом ограничишь только docker-сеть
    }
}
